# .github/workflows/daily-notification.yml
name: Daily Quote Notification

on:
  schedule:
    - cron: "01 12 * * *"
  workflow_dispatch: # Optional: Allows manual triggering

jobs:
  trigger-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger notification endpoint
        run: curl -sSf https://quote-dusky.vercel.app/api/cron/daily-notifications
